name: CI

on: [push, workflow_dispatch]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - name: Set up venv
        run: |
          python3 -m venv "$PWD/venv"
          echo "$PWD/venv/bin" >> "$GITHUB_PATH"
      - name: Install dependencies
        run: python -m pip install --upgrade pip '.[test]' '.[lint]'
      - name: Test
        run: ./.github/run.sh --no-lint
      - name: Lint
        run: ./.github/run.sh --no-test
